// <auto-generated />
using System;
using CriptoBiyuya.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CriptoBiyuya.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250607213101_MayorPrecisionDecimales")]
    partial class MayorPrecisionDecimales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CriptoBiyuya.Models.Client", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CriptoBiyuya.Models.Transaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("client_id")
                        .HasColumnType("int");

                    b.Property<int?>("clientid")
                        .HasColumnType("int");

                    b.Property<decimal>("crypto_amount")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("crypto_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("datetime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("money")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("clientid");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CriptoBiyuya.Models.Transaction", b =>
                {
                    b.HasOne("CriptoBiyuya.Models.Client", "client")
                        .WithMany("transactions")
                        .HasForeignKey("clientid");

                    b.Navigation("client");
                });

            modelBuilder.Entity("CriptoBiyuya.Models.Client", b =>
                {
                    b.Navigation("transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
